name: Deploy to Workshop

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project

      - name: Upload to Workshop
        uses: CFC-Servers/gmod-upload@master
        with:
          id: 2782407502
          changelog: "${{ github.event.head_commit.message }}"
          title: "[ACF] Removed Models"
          type: "model"
          tag1: "build"
          tag2: "fun"
          tag3: "realism"
        env:
          STEAM_USERNAME: ${{ secrets.ACF_STEAM_ACCOUNT }}
          STEAM_PASSWORD: ${{ secrets.ACF_STEAM_PASSWORD }}